blank_issues_enabled: true
contact_links:
  - name: Scuffle Discord
    url: https://discord.gg/scuffle
    about: Join our Discord for general questions as well as direct contact with the developers
